# Generated by Django 6.1 on 2026-08-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergejob',
            name='merged_css',
            field=models.TextField(blank=True, default=''),
        ),
    ]
